### ISSUE TITLE
1.1.0 - spewing out errors regarding `angularRequireDependencyOrder`

### ISSUE THREAD

**Issue by kasperlewau** [tregusti/jscs-angular#21]
> `angular-jscs: ^1.0.0` (tyvm glenn!) in package.json. 

Minor version bump introduced the following error on our end (19 occurences across ~250 files):

```
Error running rule angularRequireDependencyOrder: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'type' of undefined
    at module.exports (/Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder/utils/dependenciesFromInjectionPoint.js:26:17)
    at parseWithName (/Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder/componentMatcher.js:27:11)
    at module.exports (/Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder/componentMatcher.js:12:12)
    at /Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder.js:20:23
    at Array.forEach (native)
    at /Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder.js:19:14
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/kasperlewau/code/work/casino-saga/web/node_modules/grunt-jscs/node_modules/jscs/lib/js-file.js:426:42)
    at check (/Users/kasperlewau/code/work/casino-saga/web/node_modules/jscs-angular/src/rules/angularRequireDependencyOrder.js:18:8)
    at null.<anonymous> (/Users/kasperlewau/code/work/casino-saga/web/node_modules/grunt-jscs/node_modules/jscs/lib/string-checker.js:141:22) at app/scripts/services/activities.js :
     1 |(function () {
--------^
     2 |  'use strict';
     3 |
```

**Comment by kasperlewau** [comment]
Stepping back to `jscs-angular: 1.0.2` solved the aforementioned issue on our end.

**Comment by tregusti** [comment]
Thank you! Will check on it!
